/*
=================================================================================
DDL Script: Create Bronze Tables
=================================================================================
Script Purpose:
  This script creates tables in the 'bronze' schema, dropping existing tables 
  if they already exists.
  Run this script to re-define the DDL structure of 'bronze' Tables
=================================================================================
*/

IF OBJECT_ID ('bronze.crm_cust_info' , 'U') IS NOT NULL
	DROP TABLE bronze.crm_cust_info;
Create Table bronze.crm_cust_info(
	cst_id INT,
	cst_key NVARCHAR (50),
	cst_firstname NVARCHAR(50),
	cst_lastname NVARCHAR(50),
	cst_material_status NVARCHAR(50),
	cst_gndr NVARCHAR(50),
	cst_create_date DATE
)

IF OBJECT_ID ('bronze.crm_prd_info' , 'U') IS NOT NULL
	DROP TABLE bronze.crm_prd_info;
Create Table bronze.crm_prd_info(
	prd_id INT,
	prd_key NVARCHAR(50),
	prd_nm NVARCHAR(50),
	prd_cost INT,
	prd_line NVARCHAR(50),
	prd_start_dt DATETIME,
	prd_end_dt DATETIME
);

IF OBJECT_ID ('bronze.crm_sales_details' , 'U') IS NOT NULL
	DROP TABLE bronze.crm_sales_details;
Create Table bronze.crm_sales_details(
	sls_ord_num NVARCHAR(50),
	sls_prd_key NVARCHAR(50),
	sls_cust_id INT,
	sls_order_dt INT,
	sls_ship_dt INT,
	sls_due_dt INT,
	sls_sales INT,
	sls_quantity INT,
	sls_price INT
);

IF OBJECT_ID ('bronze.erp_loc_a101' , 'U') IS NOT NULL
	DROP TABLE bronze.erp_loc_a101;
Create Table bronze.erp_loc_a101 (
	cid NVARCHAR(50),
	cntry NVARCHAR(50)
);

IF OBJECT_ID ('bronze.erp_cust_az12' , 'U') IS NOT NULL
	DROP TABLE bronze.erp_cust_az12;
Create Table bronze.erp_cust_az12 (
	cid NVARCHAR(50),
	bdate DATE,
	gen NVARCHAR(50)
);

IF OBJECT_ID ('bronze.erp_px_cat_g1v2' , 'U') IS NOT NULL
	DROP TABLE bronze.erp_px_cat_g1v2;
Create Table bronze.erp_px_cat_g1v2 (
	id	NVARCHAR(50),
	cat NVARCHAR(50),
	subcat NVARCHAR(50),
	maintenance NVARCHAR(50)
);

CREATE OR ALTER PROCEDURE Bronze.load_bronze As
BEGIN
	DECLARE @start_time DATETIME, @end_time DATETIME
	BEGIN TRY
			PRINT '=================================================================================';
			PRINT 'Loading Bronze Layer';
			PRINT '=================================================================================';

			PRINT '---------------------------------------------------------------------------------';
			PRINT 'Loading CRM Tables';
			PRINT '---------------------------------------------------------------------------------';

			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.crm_cust_info'
			TRUNCATE TABLE Bronze.crm_cust_info;

			PRINT '>> Inserting Data Into: bronze.crm_cust_info'
			BULK INSERT Bronze.crm_cust_info
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_crm\cust_info.csv'
			WITH( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';
			

			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.crm_prd_info'
			TRUNCATE TABLE Bronze.crm_prd_info;

			PRINT '>> Inserting Data Into: bronze.crm_prd_info'
			BULK INSERT Bronze.crm_prd_info
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_crm\prd_info.csv'
			WITH (
					FIRSTROW = 2,
					FIELDTERMINATOR = ',',
					TABLOCK
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';
			
			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.crm_sales_details'
			TRUNCATE TABLE Bronze.crm_sales_details;

			PRINT '>> Inserting Data Into: bronze.crm_sales_details'
			BULK INSERT Bronze.crm_sales_details
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_crm\sales_details.csv'
			WITH (
					FIRSTROW = 2,
					FIELDTERMINATOR = ',',
					TABLOCK
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';


			
			PRINT '---------------------------------------------------------------------------------';
			PRINT 'Loading ERP Tables';
			PRINT '---------------------------------------------------------------------------------';

			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.erp_cust_az12'
			TRUNCATE TABLE Bronze.erp_cust_az12;

			PRINT '>> Inserting Data Into: bronze.erp_cust_az12'
			BULK INSERT Bronze.erp_cust_az12
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_erp\cust_az12.csv'
			WITH (
					FIRSTROW = 2,
					FIELDTERMINATOR = ',',
					TABLOCK
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';


			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.erp_loc_a101'
			TRUNCATE TABLE Bronze.erp_loc_a101;

			PRINT '>> Inserting Data Into: bronze.erp_loc_a101'
			BULK INSERT Bronze.erp_loc_a101
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_erp\loc_a101.csv'
			WITH (
					FIRSTROW = 2,
					FIELDTERMINATOR = ',',
					TABLOCK
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';

			set @start_time = GETDATE();
			PRINT '>> Truncating Table: bronze.erp_px_cat_g1v2'
			TRUNCATE TABLE Bronze.erp_px_cat_g1v2;

			PRINT '>> Inserting Data Into: bronze.erp_px_cat_g1v2'
			BULK INSERT Bronze.erp_px_cat_g1v2
			FROM 'D:\Sql Data Warehouse Project\sql-data-warehouse-project\datasets\source_erp\px_cat_g1v2.csv'
			WITH (
					FIRSTROW = 2,
					FIELDTERMINATOR = ',',
					TABLOCK
			);
			set @end_time = GETDATE();
			PRINT '>> Load Duration; ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + 'seconds';
			PRINT '>> ----------------------';


	END TRY
	BEGIN CATCH
	PRINT '============================================='
	PRINT 'ERROR OCCURED DURING LOADING BRONZE LAYER'
	PRINT 'Error Message' + ERROR_MESSAGE();
	PRINT 'Error Message' + CAST (ERROR_NUMBER() AS NVARCHAR);
	PRINT 'Error Message' + CAST (ERROR_STATE() AS NVARCHAR);
	PRINT '============================================='

	END CATCH
END;

